Add: ユーザー一覧画面の作成
NewBeLab/NewBeLab-Vue pull request #26
Opened 2023-01-14 08:03 UTC by nyohoo

# issue
#4

# やったこと
- `/profiles`のエンドポイントを叩き、ユーザー一覧のデータを取得
- 取得したデータをカード形式で一覧表示
- ページネーションの実装

# 今回のスコープに含めなかったもの
- githubの`username`を利用して草情報を表示する
- プロフィール情報から絞り込み表示

# 確認結果
<img width="1920" alt="スクリーンショット 2023-01-14 16 59 34" src="https://user-images.githubusercontent.com/62694188/212462418-0a777eda-2fd1-4e13-b6f7-8a557f4c0d71.png">

# 確認をお願いしたい点
レビューにそれほどリソース割けないと思うので、基本的な動作確認（seedデータ作成後に表示できるか等）をお願いしたいです。
また、コードで気になる点や、デザイン面でのご指摘あればお願いします。
個人的にはカードの表示がドデカすぎるところは直したいな・・・と思っています。

2023-01-14 14:52 UTC, nyohoo commented
# 追加実装（土下座）
PRを分けようかなーと思ったのですが、ややこしくなりそうなのでこちらにまとめます・・・

[Add: Githubのusernameを利用した表示の実装](https://github.com/NewBeLab/NewBeLab-Vue/pull/26/commits/690c7d4d152c3c5f0b81ba804de54722423746a2)

# やったこと
- Cardクリック時に草情報＆Githubへのリンクを表示させる

# 動作確認
https://user-images.githubusercontent.com/62694188/212477871-cbe1356e-d160-48d7-8b88-b3bf9a37c4d4.mov

2023-01-15 11:49 UTC, yoiyoicho requested changes
一覧画面、おしゃれに作っていただきありがとうございます。
動作確認は問題ナシでした👍 おつかれさまでしたー！
やはりその人の草が見えると面白さマシマシですね！
2点気になった点コメントさせていただいたので、ご確認よろしくお願いいたします！

2023-01-15 11:49 UTC, yoiyoicho commented on src/components/views/User.vue
> +        .filter((user) => user.id !== authStore.user.id)
この部分ですが、ユーザー一覧から自分のプロフィールは省くということですよね
`filter`が働いてなかったのでご確認よろしくお願いいたします！

2023-01-15 22:57 UTC, nyohoo commented
@yoiyoicho 
レビューありがとうございます！
ご指摘いただいた点について対応＆コメントで返信しました。
お手隙でご確認お願いします🙏

2023-01-16 03:14 UTC, yoiyoicho commented
早速の修正ありがとうございました！
LGTMですのでマージお願いいたします！

2023-01-16 03:15 UTC, yoiyoicho commented on src/components/views/User.vue
> +              </p>
https://github.com/NewBeLab/NewBeLab-Vue/pull/26/commits/c6fc0ccafcd60bc8f31232cb0a39ce55600e2ce5 にて対応済

2023-01-16 03:15 UTC, yoiyoicho commented on src/components/views/User.vue
> +        .filter((user) => user.id !== authStore.user.id)
https://github.com/NewBeLab/NewBeLab-Vue/pull/26/commits/c6fc0ccafcd60bc8f31232cb0a39ce55600e2ce5 にて対応済（`filter`しない）

2023-01-16 09:18 UTC, merged